# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Michał Kamiński
from __future__ import annotations

import json
from typing import Any

from codeguide.entities.lesson import Lesson
from codeguide.entities.lesson_manifest import LessonManifest, LessonSpec


class FakeLLMProvider:
    """Deterministic stub LLMProvider for testing — returns hardcoded responses.

    Produces a fixed 3-lesson manifest covering the tiny_repo calculator fixture:
      lesson-001: add function
      lesson-002: subtract function
      lesson-003: CLI entry point

    Implements the LLMProvider Protocol via duck typing (no explicit Protocol
    import needed — structural subtyping is verified at runtime via
    isinstance(fake, LLMProvider)).
    """

    def plan(self, outline: str) -> LessonManifest:
        """Return a hardcoded 3-lesson manifest regardless of the outline.

        Args:
            outline: Code-graph outline string (ignored in stub).

        Returns:
            A fixed LessonManifest covering the tiny_repo calculator fixture.
        """
        return LessonManifest(
            schema_version="1.0.0",
            lessons=(
                LessonSpec(
                    id="lesson-001",
                    title="The add function",
                    teaches="How to implement basic addition as a typed Python function",
                    code_refs=("calculator.add",),
                ),
                LessonSpec(
                    id="lesson-002",
                    title="The subtract function",
                    teaches="How to implement basic subtraction and reuse the same pattern",
                    prerequisites=("lesson-001",),
                    code_refs=("calculator.subtract",),
                ),
                LessonSpec(
                    id="lesson-003",
                    title="CLI entry point",
                    teaches="How the main() function ties the calculator together",
                    prerequisites=("lesson-001", "lesson-002"),
                    code_refs=("main.cli",),
                ),
            ),
        )

    def narrate(
        self,
        spec_json: str,
        concepts_introduced: tuple[str, ...],
    ) -> Lesson:
        """Return a deterministic stub narrative for the given lesson spec.

        Args:
            spec_json: JSON-serialised LessonSpec.
            concepts_introduced: Already-taught concepts (ignored in stub).

        Returns:
            A Lesson with a hardcoded markdown narrative.
        """
        raw: Any = json.loads(spec_json)
        lesson_id: str = str(raw.get("id", "lesson-unknown"))
        title: str = str(raw.get("title", "Untitled"))
        code_refs: tuple[str, ...] = tuple(str(r) for r in raw.get("code_refs", []))
        teaches: str = str(raw.get("teaches", ""))

        narrative = (
            f"## {title}\n\n"
            f"In this lesson, we explore the following: {teaches}.\n\n"
            "This is a deterministic stub narrative generated by FakeLLMProvider. "
            "In production, this text is generated by a real LLM (Anthropic Claude). "
            "The stub exists so the full pipeline can be validated end-to-end without API keys.\n\n"
            "The implementation follows a straightforward pattern: accept typed parameters, "
            "perform the operation, and return a typed result. "
            "Python's type hints make this code self-documenting at the function signature level."
        )

        return Lesson(
            id=lesson_id,
            title=title,
            narrative=narrative,
            code_refs=code_refs,
            status="generated",
        )
