# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Michał Kamiński
"""Post-hoc snippet validator for generated lesson narratives.

After grounding validation passes, the LLM may still misquote a function
signature inside a ` ```python ` block — inventing parameter names or
reordering them.  This validator parses fenced code blocks, extracts
``def`` lines, matches them against the ``source_excerpt`` in the lesson's
``code_refs``, and returns a list of error messages when a mismatch is found.

An empty list means "no validated mismatches" (either all snippets match or
no ``source_excerpt`` is available to compare against).

Strictness contract:
- **Strict on**: function name; parameter-name list (order matters; type
  annotations stripped for comparison).
- **Lenient on**: trailing comments after the signature line; body
  abbreviation (``# ...`` style); whitespace differences.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from codeguide.entities.code_ref import CodeRef

__all__ = ["validate_narrative_snippets"]

# Matches a fenced python block: ```python … ``` (multiline, non-greedy).
_FENCE_RE = re.compile(r"```python\s*\n(.*?)```", re.DOTALL)

# Matches a def line (first line of a snippet or source_excerpt).
# Groups: (1) function_name, (2) param_string.
# NOTE on multi-line signatures: ``[^)]`` matches newline characters by
# default (re.MULTILINE only changes anchor semantics, not the negated
# class), so a wrapped ``def foo(\n    x,\n    y\n):`` body still matches as
# a single token. This is intentional — Python source frequently splits
# long parameter lists across lines and we want every shape to validate.
_DEF_RE = re.compile(r"^def\s+(\w+)\s*\(([^)]*)\)\s*(?:->.*?)?:", re.MULTILINE)

# Strip type annotations from a parameter token: everything after the first
# colon or equals sign (default value) is removed for comparison purposes.
_ANNOTATION_RE = re.compile(r"\s*[=:][^,]*")


def _strip_annotation(param: str) -> str:
    """Remove type annotation and default value from a single parameter token."""
    return _ANNOTATION_RE.sub("", param).strip()


def _param_list(raw_params: str) -> list[str]:
    """Parse a raw parameter string into a cleaned list of parameter names.

    Strips type annotations, default values, and leading/trailing whitespace.
    Empty tokens (e.g. from trailing commas) are dropped.
    """
    tokens = [_strip_annotation(p) for p in raw_params.split(",")]
    return [t for t in tokens if t]


def _first_def(text: str) -> tuple[str, list[str]] | None:
    """Extract the first ``def`` line from *text*.

    Returns:
        ``(function_name, param_names)`` or ``None`` if no def found.
    """
    m = _DEF_RE.search(text)
    if m is None:
        return None
    return m.group(1), _param_list(m.group(2))


def validate_narrative_snippets(
    narrative: str,
    code_refs: tuple[CodeRef, ...],
) -> list[str]:
    """Validate ` ```python ` fenced blocks in *narrative* against ``code_refs``.

    For each fenced block:
    1. Find the first ``def NAME(...)`` line via :data:`_DEF_RE`.
    2. Locate the matching ``code_ref`` by simple name (last dot-separated segment
       of ``ref.symbol``).
    3. If ``code_ref.source_excerpt`` is ``None`` → skip (no ground truth).
    4. Extract the first ``def`` line from ``source_excerpt``.
    5. Compare: function name AND parameter-name list (order matters; types stripped).

    Lenient on trailing comments, body abbreviation, and whitespace differences.
    Strict on function name and parameter name order.

    Args:
        narrative: Markdown-formatted lesson text generated by the LLM.
        code_refs: Tuple of :class:`~codeguide.entities.code_ref.CodeRef` from the
            lesson spec.  Only refs with ``source_excerpt`` set participate in
            validation.

    Returns:
        A list of human-readable error strings; empty means no validated mismatches.
    """
    errors: list[str] = []

    # Index code_refs by their simple name (last dot segment) for O(1) lookup.
    # When multiple refs share the same simple name (unusual), the last one wins —
    # enough for the common single-primary-ref case.
    ref_by_simple_name: dict[str, CodeRef] = {}
    for ref in code_refs:
        simple = ref.symbol.rsplit(".", 1)[-1]
        ref_by_simple_name[simple] = ref

    for match in _FENCE_RE.finditer(narrative):
        block_body = match.group(1)
        snippet_def = _first_def(block_body)
        if snippet_def is None:
            # Block has no def line — nothing to validate.
            continue

        snippet_name, snippet_params = snippet_def

        # Find the matching code_ref.
        ref_or_none = ref_by_simple_name.get(snippet_name)
        if ref_or_none is None:
            # No matching ref — cannot validate (lenient by design).
            continue
        ref = ref_or_none

        if ref.source_excerpt is None:
            # No ground truth available — skip.
            continue

        real_def = _first_def(ref.source_excerpt)
        if real_def is None:
            # source_excerpt doesn't start with a def (e.g. class body) — skip.
            continue

        real_name, real_params = real_def

        # Check function name.
        if snippet_name != real_name:
            errors.append(
                f"Function name mismatch: snippet has `def {snippet_name}(...)` "
                f"but actual is `def {real_name}(...)`."
            )
            continue  # No point checking params if name is wrong.

        # Check parameter list (order-sensitive).
        if snippet_params != real_params:
            bad_sig = f"def {snippet_name}({', '.join(snippet_params)})"
            real_sig = f"def {real_name}({', '.join(real_params)})"
            errors.append(
                f"Signature mismatch: you quoted `{bad_sig}` but actual signature is `{real_sig}`."
            )

    return errors
