// Sample content based on kennethreitz/requests
// Lessons are clustered into concept groups.

window.TUTORIAL_META = {
  project_name: "requests",
  owner: "kennethreitz",
  commit: "a1b2c3d",
  branch: "main",
  generated_at: "2026-04-18 14:22 UTC",
  wiedunflow_version: "0.1.0",
  schema_version: "1.0.0",
  file_count: 47,
  total_lessons: 12,
  resolution: 87, // percent
  cost_haiku: 0.42,
  cost_opus: 1.87,
  elapsed_seconds: 1423,
  doc_coverage: 78,
};

window.TUTORIAL_CLUSTERS = [
  {
    id: "foundations",
    label: "Foundations",
    kicker: "Part 1",
    description: "The shape of the library — what you touch when you call requests.get().",
    lessons: ["overview", "api-surface", "sessions"],
  },
  {
    id: "request-lifecycle",
    label: "Request lifecycle",
    kicker: "Part 2",
    description: "From a PreparedRequest through adapters and back as a Response.",
    lessons: ["prepared-request", "adapters", "response"],
  },
  {
    id: "internals",
    label: "Internals & utilities",
    kicker: "Part 3",
    description: "Authentication, cookies, and the model layer that glues it together.",
    lessons: ["models", "auth", "cookies", "utils"],
  },
  {
    id: "closing",
    label: "Where to go next",
    kicker: "Wrap-up",
    description: "Pointers for deeper reading — and what this tutorial intentionally skipped.",
    lessons: ["exceptions", "next"],
  },
];

window.TUTORIAL_LESSONS = [
  {
    id: "overview",
    cluster: "foundations",
    title: "A library that hides HTTP's sharp edges",
    subtitle: "Why requests exists, and the shape of its public API.",
    read_time: 3,
    words: 612,
    confidence: "high",
    narration: [
      { kind: "p", text: "The <code>requests</code> library's stated goal is disarmingly simple: make HTTP interactions that a developer performs hundreds of times a week feel like the one-liners they conceptually are. It wraps <code>urllib3</code>, which wraps Python's <code>http.client</code>, which wraps a socket. Each layer hides something that the layer above it should not have to think about — connection pools, chunked transfer encoding, certificate bundles, redirects, content decoding. By the time you reach <code>requests.get(url)</code>, almost every decision has been made for you." },
      { kind: "p", text: "The public surface is tiny. There are seven module-level verbs — <code>get</code>, <code>post</code>, <code>put</code>, <code>patch</code>, <code>delete</code>, <code>head</code>, <code>options</code> — and one generic <code>request()</code> that all of them delegate to. Everything else in the package exists to support the internal journey between that call and the <code>Response</code> object you receive back." },
      { kind: "p", text: "This first lesson walks you through that public entry point. It is deliberately shallow: the point is to fix a vocabulary — <em>api</em>, <em>session</em>, <em>adapter</em>, <em>prepared request</em>, <em>response</em> — before we open any of those boxes. Once you recognise those five words and the order they appear in, the rest of the codebase reads like a story." },
      { kind: "p", text: "If you have used <code>requests</code> before, the opening of <code>api.py</code> will look almost offensively short. That is the point. The module is 163 lines long. You will have read all of it before you finish this lesson." },
    ],
    code: {
      file: "requests/api.py",
      lang: "python",
      highlight: [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
      lines: [
        "# -*- coding: utf-8 -*-",
        "",
        "\"\"\"",
        "requests.api",
        "~~~~~~~~~~~~",
        "",
        "This module implements the Requests API.",
        "\"\"\"",
        "",
        "from . import sessions",
        "",
        "",
        "def request(method, url, **kwargs):",
        "    \"\"\"Constructs and sends a :class:`Request <Request>`.",
        "",
        "    :param method: method for the new :class:`Request` object.",
        "    :param url: URL for the new :class:`Request` object.",
        "    :param params: (optional) Dictionary, list of tuples",
        "    :param data: (optional) Dictionary, list of tuples, bytes",
        "    :param json: (optional) A JSON serializable Python object",
        "    :return: :class:`Response <Response>` object",
        "    :rtype: requests.Response",
        "    \"\"\"",
        "    with sessions.Session() as session:",
        "        return session.request(method=method, url=url, **kwargs)",
        "",
        "",
        "def get(url, params=None, **kwargs):",
        "    \"\"\"Sends a GET request.\"\"\"",
        "    return request('get', url, params=params, **kwargs)",
        "",
        "",
        "def post(url, data=None, json=None, **kwargs):",
        "    \"\"\"Sends a POST request.\"\"\"",
        "    return request('post', url, data=data, json=json, **kwargs)",
      ],
    },
  },
  {
    id: "api-surface",
    cluster: "foundations",
    title: "Seven verbs, one generic",
    subtitle: "The top-level helpers all funnel into `request()`.",
    read_time: 2,
    words: 384,
    confidence: "high",
    narration: [
      { kind: "p", text: "Every module-level helper in <code>requests.api</code> is a three-line function. Each one fixes its HTTP method, forwards all keyword arguments, and returns whatever <code>request()</code> returns. This pattern is worth pausing on." },
      { kind: "p", text: "The indirection is not free — it's a deliberate choice. <code>request()</code> always opens a short-lived <code>Session</code> via a context manager. This gives the module-level helpers the same connection pooling, cookie jar, and TLS configuration that a long-lived session would provide — just scoped to a single call." },
      { kind: "p", text: "The trade-off: you pay a small setup cost per request. For applications making more than a handful of calls, moving to a reused <code>Session</code> is the first optimisation you will reach for. That is the subject of the next lesson." },
    ],
    code: {
      file: "requests/api.py",
      lang: "python",
      highlight: [2, 3, 4, 5, 9, 10, 11, 12, 16, 17, 18, 19],
      lines: [
        "def get(url, params=None, **kwargs):",
        "    \"\"\"Sends a GET request.\"\"\"",
        "    kwargs.setdefault('allow_redirects', True)",
        "    return request('get', url, params=params, **kwargs)",
        "",
        "",
        "def options(url, **kwargs):",
        "    \"\"\"Sends an OPTIONS request.\"\"\"",
        "    kwargs.setdefault('allow_redirects', True)",
        "    return request('options', url, **kwargs)",
        "",
        "",
        "def head(url, **kwargs):",
        "    \"\"\"Sends a HEAD request.\"\"\"",
        "    kwargs.setdefault('allow_redirects', False)",
        "    return request('head', url, **kwargs)",
        "",
        "",
        "def post(url, data=None, json=None, **kwargs):",
        "    \"\"\"Sends a POST request.\"\"\"",
        "    return request('post', url, data=data, json=json, **kwargs)",
      ],
    },
  },
  {
    id: "sessions",
    cluster: "foundations",
    title: "Session — the real entry point",
    subtitle: "State, connection pools, and why you reuse one.",
    read_time: 4,
    words: 724,
    confidence: "high",
    narration: [
      { kind: "p", text: "<code>Session</code> is where <code>requests</code> starts keeping state. If <code>api.py</code> is the shop window, <code>sessions.py</code> is the floor you walk across to reach the counter. A session holds default headers, cookies accumulated across calls, authentication, a transport adapter per URL prefix, and — importantly — a connection pool via <code>HTTPAdapter</code>." },
      { kind: "p", text: "The constructor is almost entirely attribute initialisation. The interesting methods are <code>prepare_request()</code>, which turns a user-facing <code>Request</code> into a <code>PreparedRequest</code> that the adapters understand, and <code>send()</code>, which hands that prepared request to the adapter and interprets the result." },
      { kind: "p", text: "Reusing a session across many calls unlocks keep-alive at the TCP level and TLS session resumption. The cost of the first request amortises; subsequent requests to the same host skip a full handshake. For anything beyond a quick script this is not an optimisation — it's the correct default." },
    ],
    code: {
      file: "requests/sessions.py",
      lang: "python",
      highlight: [8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
      lines: [
        "class Session(SessionRedirectMixin):",
        "    \"\"\"A Requests session.",
        "",
        "    Provides cookie persistence, connection-pooling, and configuration.\"\"\"",
        "",
        "    __attrs__ = [...]",
        "",
        "    def __init__(self):",
        "        self.headers = default_headers()",
        "        self.auth = None",
        "        self.proxies = {}",
        "        self.hooks = default_hooks()",
        "        self.params = {}",
        "        self.stream = False",
        "        self.verify = True",
        "        self.cert = None",
        "        self.max_redirects = DEFAULT_REDIRECT_LIMIT",
        "        self.trust_env = True",
        "        self.cookies = cookiejar_from_dict({})",
        "        self.adapters = OrderedDict()",
        "        self.mount('https://', HTTPAdapter())",
        "        self.mount('http://', HTTPAdapter())",
      ],
    },
  },
  {
    id: "prepared-request",
    cluster: "request-lifecycle",
    title: "PreparedRequest — the wire-ready object",
    subtitle: "Where headers, URL and body are normalised.",
    read_time: 4,
    words: 812,
    confidence: "high",
    narration: [
      { kind: "p", text: "A <code>Request</code> is what the user wrote. A <code>PreparedRequest</code> is what actually leaves the machine. The difference is exactly the set of transformations the library has to apply to make your intent valid HTTP: URL encoding, query-string merging, cookie injection, content-type inference, authentication signing." },
      { kind: "p", text: "This split — user-facing <em>intent</em> object and wire-ready <em>concrete</em> object — is one of the most portable ideas in the library. It cleanly separates the ergonomic API from the invariants the adapters depend on. Every adapter can assume its input is already valid." },
    ],
    code: {
      file: "requests/models.py",
      lang: "python",
      highlight: [10, 11, 12, 13, 14, 15, 16, 17],
      lines: [
        "class PreparedRequest(RequestEncodingMixin, RequestHooksMixin):",
        "    \"\"\"The fully mutable :class:`PreparedRequest <PreparedRequest>` object,",
        "    containing the exact bytes that will be sent to the server.\"\"\"",
        "",
        "    def __init__(self):",
        "        self.method = None",
        "        self.url = None",
        "        self.headers = None",
        "        self._cookies = None",
        "        self.body = None",
        "        self.hooks = default_hooks()",
        "        self._body_position = None",
        "",
        "    def prepare(self, method=None, url=None, headers=None,",
        "                files=None, data=None, params=None, auth=None,",
        "                cookies=None, hooks=None, json=None):",
        "        \"\"\"Prepares the entire request with the given parameters.\"\"\"",
        "        self.prepare_method(method)",
        "        self.prepare_url(url, params)",
      ],
    },
  },
  {
    id: "adapters",
    cluster: "request-lifecycle",
    title: "HTTPAdapter — the connection pool",
    subtitle: "Where requests meets urllib3.",
    read_time: 5,
    words: 980,
    confidence: "medium",
    narration: [
      { kind: "p", text: "<code>HTTPAdapter</code> is the boundary between <code>requests</code> and <code>urllib3</code>. Everything above it speaks in <code>PreparedRequest</code> and <code>Response</code>; everything below it speaks in <code>urllib3</code>'s connection pool manager. The adapter translates between the two." },
      { kind: "p", text: "The most important method is <code>send()</code>. It picks the right pool, issues the request, and builds a <code>Response</code>. The two hooks you will most often override are <code>init_poolmanager</code> (for custom SSL contexts or proxy setups) and <code>proxy_manager_for</code>." },
    ],
    code: {
      file: "requests/adapters.py",
      lang: "python",
      highlight: [3, 4, 5, 6, 7, 8, 9, 10],
      lines: [
        "class HTTPAdapter(BaseAdapter):",
        "    \"\"\"The built-in HTTP Adapter for urllib3.\"\"\"",
        "",
        "    def __init__(self, pool_connections=DEFAULT_POOLSIZE,",
        "                 pool_maxsize=DEFAULT_POOLSIZE,",
        "                 max_retries=DEFAULT_RETRIES,",
        "                 pool_block=DEFAULT_POOLBLOCK):",
        "        self.max_retries = Retry.from_int(max_retries)",
        "        self.config = {}",
        "        self.proxy_manager = {}",
        "",
        "        super().__init__()",
        "",
        "        self._pool_connections = pool_connections",
        "        self._pool_maxsize = pool_maxsize",
        "        self._pool_block = pool_block",
        "",
        "        self.init_poolmanager(pool_connections, pool_maxsize,",
        "                              block=pool_block)",
      ],
    },
  },
  {
    id: "response",
    cluster: "request-lifecycle",
    title: "Response — laziness as a feature",
    subtitle: "Content, decoding, streaming and iter_content.",
    read_time: 4,
    words: 704,
    confidence: "high",
    narration: [
      { kind: "p", text: "The <code>Response</code> object is where <code>requests</code>' pragmatism shows most. Headers are parsed eagerly because they're cheap. Bodies are not — they're streamed from the socket on demand, decoded only when you access <code>.text</code> or <code>.json()</code>, and cached thereafter." },
      { kind: "p", text: "This laziness is what lets the library scale from one-line scripts to servers pushing gigabytes. The same <code>Response</code> object serves both cases; the consumer picks the access pattern." },
    ],
    code: {
      file: "requests/models.py",
      lang: "python",
      highlight: [5, 6, 7, 8, 9, 10, 11, 12],
      lines: [
        "class Response:",
        "    \"\"\"The :class:`Response <Response>` object, which contains a",
        "    server's response to an HTTP request.\"\"\"",
        "",
        "    __attrs__ = [",
        "        '_content', 'status_code', 'headers', 'url', 'history',",
        "        'encoding', 'reason', 'cookies', 'elapsed', 'request',",
        "    ]",
        "",
        "    def __init__(self):",
        "        self._content = False",
        "        self._content_consumed = False",
        "        self._next = None",
        "        self.status_code = None",
        "        self.headers = CaseInsensitiveDict()",
        "        self.encoding = None",
        "        self.history = []",
        "        self.elapsed = datetime.timedelta(0)",
        "        self.request = None",
      ],
    },
  },
  {
    id: "models",
    cluster: "internals",
    title: "Models — Request, PreparedRequest, Response",
    subtitle: "The three data classes that carry everything.",
    read_time: 3,
    words: 520,
    confidence: "high",
    narration: [
      { kind: "p", text: "<code>models.py</code> is the quiet centre of the codebase. Three classes live here — <code>Request</code>, <code>PreparedRequest</code>, and <code>Response</code> — and almost every other module touches at least one of them." },
    ],
    code: {
      file: "requests/models.py",
      lang: "python",
      highlight: [1, 2, 3, 4, 5],
      lines: [
        "class Request(RequestHooksMixin):",
        "    \"\"\"A user-created :class:`Request <Request>` object.",
        "",
        "    Used to prepare a :class:`PreparedRequest <PreparedRequest>`,",
        "    which is sent to the server.\"\"\"",
        "",
        "    def __init__(self,",
        "                 method=None, url=None, headers=None, files=None,",
        "                 data=None, params=None, auth=None, cookies=None,",
        "                 hooks=None, json=None):",
        "        data = [] if data is None else data",
        "        files = [] if files is None else files",
        "        params = {} if params is None else params",
        "        hooks = {} if hooks is None else hooks",
        "",
        "        self.hooks = default_hooks()",
        "            self.register_hook(event=k, hook=v)",
      ],
    },
  },
  {
    id: "auth",
    cluster: "internals",
    title: "Authentication handlers",
    subtitle: "Pluggable callables that mutate a PreparedRequest.",
    read_time: 3,
    words: 468,
    confidence: "high",
    narration: [
      { kind: "p", text: "Auth in <code>requests</code> is a callable. Any object that accepts a <code>PreparedRequest</code> and returns it (possibly modified) is a valid auth handler. <code>HTTPBasicAuth</code> and <code>HTTPDigestAuth</code> are shipped; everything else is a plugin boundary you are free to implement." },
    ],
    code: {
      file: "requests/auth.py",
      lang: "python",
      highlight: [1, 2, 3, 4, 5, 6, 7, 8],
      lines: [
        "class HTTPBasicAuth(AuthBase):",
        "    \"\"\"Attaches HTTP Basic Authentication to the given Request.\"\"\"",
        "",
        "    def __init__(self, username, password):",
        "        self.username = username",
        "        self.password = password",
        "",
        "    def __call__(self, r):",
        "        r.headers['Authorization'] = _basic_auth_str(",
        "            self.username, self.password)",
        "        return r",
      ],
    },
  },
  {
    id: "cookies",
    cluster: "internals",
    title: "Cookies — a jar and a dict",
    subtitle: "RequestsCookieJar bridges http.cookiejar and dict ergonomics.",
    read_time: 3,
    words: 512,
    confidence: "medium",
    narration: [
      { kind: "p", text: "<code>RequestsCookieJar</code> subclasses <code>http.cookiejar.CookieJar</code> and adds dict-style access. You can iterate, slice by domain, and do <code>jar['session']</code> — all while the underlying RFC-compliant jar tracks expiry and paths correctly." },
    ],
    code: {
      file: "requests/cookies.py",
      lang: "python",
      highlight: [1, 2, 3, 4, 5],
      lines: [
        "class RequestsCookieJar(cookielib.CookieJar, MutableMapping):",
        "    \"\"\"Compatibility class; is a cookielib.CookieJar, but exposes",
        "    a dict interface. This is the CookieJar we create by default for",
        "    requests and sessions that don't specify one, since some clients",
        "    may expect response.cookies and session.cookies to support",
        "    dict operations.\"\"\"",
      ],
    },
  },
  {
    id: "utils",
    cluster: "internals",
    title: "Utilities — the plumbing drawer",
    subtitle: "Small functions doing the unglamorous work.",
    read_time: 2,
    words: 340,
    confidence: "medium",
    narration: [
      { kind: "p", text: "<code>utils.py</code> collects dozens of small helpers: URL parsing, environment-variable lookup, netrc handling, default user-agent strings. None of them are interesting on their own. Collectively they are what keeps the main modules readable." },
    ],
    code: {
      file: "requests/utils.py",
      lang: "python",
      highlight: [1, 2, 3, 4, 5],
      lines: [
        "def default_user_agent(name='python-requests'):",
        "    \"\"\"Return a string representing the default user agent.\"\"\"",
        "    return f'{name}/{__version__}'",
        "",
        "",
        "def default_headers():",
        "    return CaseInsensitiveDict({",
        "        'User-Agent': default_user_agent(),",
        "        'Accept-Encoding': DEFAULT_ACCEPT_ENCODING,",
        "        'Accept': '*/*',",
        "        'Connection': 'keep-alive',",
        "    })",
      ],
    },
  },
  {
    id: "exceptions",
    cluster: "closing",
    title: "Exception taxonomy",
    subtitle: "One root, a flat tree, catchable at any level.",
    read_time: 2,
    words: 296,
    confidence: "high",
    narration: [
      { kind: "p", text: "Everything <code>requests</code> raises inherits from <code>RequestException</code>. That single root lets callers write one <code>except</code> clause and catch anything the library could throw — while the specific subclasses (<code>Timeout</code>, <code>ConnectionError</code>, <code>HTTPError</code>) remain available for finer control." },
    ],
    code: {
      file: "requests/exceptions.py",
      lang: "python",
      highlight: [1, 2, 3, 4, 5, 6, 7],
      lines: [
        "class RequestException(IOError):",
        "    \"\"\"There was an ambiguous exception that occurred while handling",
        "    your request.\"\"\"",
        "",
        "class HTTPError(RequestException):",
        "    \"\"\"An HTTP error occurred.\"\"\"",
        "",
        "class ConnectionError(RequestException):",
        "    \"\"\"A connection error occurred.\"\"\"",
        "",
        "class Timeout(RequestException):",
        "    \"\"\"The request timed out.\"\"\"",
      ],
    },
  },
  {
    id: "next",
    cluster: "closing",
    title: "Where to go next",
    subtitle: "Files this tutorial skipped — and why you might open them.",
    read_time: 2,
    words: 310,
    confidence: "high",
    is_closer: true,
    narration: [
      { kind: "p", text: "This tutorial covered the eleven modules that handle the 90% case — the path a request takes from your keyboard to the wire and back. Five files were intentionally skipped. They are listed below with a single sentence each, and a reason you might come back for them." },
      { kind: "next-links", items: [
        { label: "requests/__version__.py", note: "Version string only — read once, then forget." },
        { label: "requests/_internal_utils.py", note: "String-type coercion helpers. Only relevant if you fork the library." },
        { label: "requests/certs.py", note: "Returns the path to the certifi CA bundle. One line of real code." },
        { label: "requests/help.py", note: "Prints platform info for bug reports. Useful when filing issues." },
        { label: "requests/status_codes.py", note: "The LookupDict for HTTP status names. Explore if you want readable literals." },
      ] },
      { kind: "p", text: "External docs worth your time: the <code>urllib3</code> user guide (especially the pool-manager and retry sections) and the <code>certifi</code> README. Both are short; both are where <code>requests</code> delegates the hard parts." },
    ],
    code: {
      file: "requests/__init__.py",
      lang: "python",
      highlight: [5, 6, 7, 8],
      lines: [
        "\"\"\"",
        "Requests HTTP Library",
        "~~~~~~~~~~~~~~~~~~~~~",
        "\"\"\"",
        "from .api import request, get, head, post, put, patch, delete, options",
        "from .sessions import session, Session",
        "from .models import Request, Response, PreparedRequest",
        "from .exceptions import RequestException, Timeout, ConnectionError",
      ],
    },
  },
];
