name: DCO

on:
  pull_request:
    branches: [main]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR commits
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Get PR commits
        id: get-pr-commits
        uses: tim-actions/get-pr-commits@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: DCO check
        uses: tim-actions/dco@v1.1.0
        with:
          commits: ${{ steps.get-pr-commits.outputs.commits }}
